version: '3.8'

services:
  # Shared PostgreSQL Database
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: mlflow_multitenant
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # Multi-Tenant Gateway
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://mlflow:mlflow123@postgres:5432/mlflow_multitenant
    depends_on:
      - postgres
    volumes:
      - ./tenants_data:/app/tenants_data

  # MLflow Server (Tenant-Aware)
  mlflow:
    build: ./mlflow
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://mlflow:mlflow123@postgres:5432/mlflow_multitenant
    depends_on:
      - postgres
    volumes:
      - ./tenants_data:/mlflow/tenants_data

  # Multi-Tenant Frontend
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - GATEWAY_URL=http://gateway:8000
    depends_on:
      - gateway
    volumes:
      - ./frontend:/app

volumes:
  postgres_data: