version: '3.8'
services:
  mlflow:
    build: ./mlflow
    ports:
      - "5001:5001"
    environment:
      - MLFLOW_BACKEND_STORE_URI=sqlite:///mlflow.db
      - MLFLOW_DEFAULT_ARTIFACT_ROOT=/mlflow/artifacts
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
    volumes:
      - ./mlflow_data:/mlflow:rw
    command: mlflow server --host 0.0.0.0 --port 5001

  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
      - ./mlflow_data:/mlflow_data
    depends_on:
      - mlflow
    command: streamlit run app.py --server.address=0.0.0.0

  jupyter:
    image: jupyter/scipy-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
